spring:
  profiles:
    active:
      - core-dev

wx:
  appID:
  token:
  encodingAESKey:

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql