spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/yoda?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      druid:
         initialSize: 5
         min-idle: 5
         max-active: 20
         max-wait: 60000
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedStatements: true
   kafka:
      bootstrap-servers: localhost:9092
      producer:
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#group-id: yodaTestGroup
   redis:
      password: null
#auto-offset-reset: earliest
      port: 6379
      pool:
         min-idle: 0
         max-total: 600
         max-wait: 1000
      host: localhost
      timeout: 100000
      jedis:
         pool:
            max-idle: 300
logging:
   level:
      org:
         springframework:
            security: INFO
      root: INFO
      sample:
         mybatis:
            mapper: INFO
   path: /var/tmp/yoda-core-log

yoda:
   file-location: /yoda/uploads/
   kafka-enabled: false

jediorder: 
   machine-id: 1022

chatter:
   base-url: http://127.0.0.1:5000
# MyBatis
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:46 :#mybatis:
# Was at begin of line:47 :#    type-aliases-package: com.zyd.blog.persistence.beans
# Was at begin of line:48 :#    mapper-locations: classpath:/mybatis/*.xml
# Was at begin of line:49 :# mapper
# Was at begin of line:50 :#mapper:
# Was at begin of line:51 :#    mappers:
# Was at begin of line:52 :#        -
# Was at begin of line:53 :#    not-empty: false
# Was at begin of line:54 :#    identity: MYSQL