server:
  port: 80
  compression:
    enabled: true

spring:
  profiles:
    include:
      - core-prod

logging:
#  level:
#    root: WARN
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    com.taklip: INFO
#    sample.mybatis.mapper: INFO
  file:
    path: /var/tmp/yoda-portal-log