name: Build and Deploy

run-name: ${{ github.repository }} is building and deploying

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build project
        run: ./gradlew clean build -x test

      # - name: Build Docker image
      #   run: docker build -t yoda-app:latest .

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Upload Docker image to server via SCP
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     source: "./yoda-app.jar"
      #     target: "~/deploy/yoda-app.jar"

      # - name: Execute remote deployment script
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: 22
      #     script: |
      #       cd ~/deploy
      #       chmod +x deploy.sh
      #       ./deploy.sh

      # - name: Build and Push Docker Image
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/yoda:latest


